### ISSUE TITLE
6.85 doesnt work

### ISSUE THREAD

**Issue by ghost** [FTCr/d2clr#2]
doesn't work since newest patch.
possible to change from having mouse click on accept to pressing return key?
that way you don't need to ever know mouse co-ordinates.

**Comment by FTCr** [comment]
I have no GNU/Linux now.
Maybe Dota 2 drops notify-send support?!

**Comment by ghost** [comment]
apologies for wasting time- false alarm. i had it set to run at startup with no x/y parameters by my oversight. dumb mistake. works fine. sorry FTCr
