### ISSUE TITLE
request keyboard enter instead of mouse click

### ISSUE THREAD

**Issue by ghost** [FTCr/d2clr#3]
hey.
are you still not using Linux anymore?

is it possible to replace the mouse click code with: 

xdotool key KP_Enter

then you don't need to know mouse co-ordinates anymore.
this also works for game ready which are off-center such as custom games.

**Comment by FTCr** [comment]
Hi. I did it already.

**Comment by ghost** [comment]
thanks, ill test it my end when i get my PC back.
